// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.CONTEXT;

#nullable disable

namespace WebApplication1.Migrations.NotizDb
{
    [DbContext(typeof(NotizDbContext))]
    [Migration("20250605164729_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonLibrary.Notiz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOntossag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feladat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HatarIdo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MikorKezdje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOTIZID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjektNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tulajdonos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Notiz");
                });
#pragma warning restore 612, 618
        }
    }
}
